org: dreissenzulu
app: coms-billing-test
# NOTE: update this with your service name
service: notes-app-2-api

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallback to what we have set in the provider section
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  tableName: ${self:custom.stage}-notes

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev 
  region: us-west-2
  
  environment:
    tableName: ${self:custom.tableName}
    stripeSecretKey: ${env:STRIPE_SECRET_KEY}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "ses:SendEmail"
      # Restrict IAM role permissions to
      # the specific table for the resource
      Resource: "*"

functions:
  create-bill:
    handler: create-bill.main
    events:
      - http:
          path: create-bill
          method: post
          cors: true
  update-bill:
    handler: update-bill.main
    events:
      - http:
          path: update-bill
          method: post
          cors: true
  encrypt-key:
    handler: encrypt-key.main
    events:
      - http:
          path: encrypt-key
          method: post
          cors: true
  ipn-handler:
    handler: ipn-handler.main
    events:
      - http:
          path: ipn-handler
          method: post
          cors: true
